
function glyphAssignment()
{
	var out = [
		{gene: 'COL3A1',	taxonomy: '0',	glyphSymbol:'>',	glyphName:'triangleRight'},
		{gene: 'PLVAP',	taxonomy: '0',	glyphSymbol:'.',	glyphName:'point'},
		{gene: 'TMEM100',	taxonomy: '0',	glyphSymbol:'v',	glyphName:'triangleDown'},
		{gene: 'HSPB7',	taxonomy: '1',	glyphSymbol:'+',	glyphName:'plus'},
		{gene: 'MYBPC3',	taxonomy: '1',	glyphSymbol:'o',	glyphName:'circle'},
		{gene: 'MYH7',	taxonomy: '1',	glyphSymbol:'v',	glyphName:'triangleDown'},
		{gene: 'MYL2',	taxonomy: '1',	glyphSymbol:'>',	glyphName:'triangleRight'},
		{gene: 'MYL3',	taxonomy: '1',	glyphSymbol:'.',	glyphName:'point'},
		{gene: 'MYOM1',	taxonomy: '1',	glyphSymbol:'h',	glyphName:'star6'},
		{gene: 'NAV1',	taxonomy: '1',	glyphSymbol:'p',	glyphName:'star5'},
		{gene: 'SLC8A1',	taxonomy: '1',	glyphSymbol:'<',	glyphName:'triangleLeft'},
		{gene: 'SORBS2',	taxonomy: '1',	glyphSymbol:'<',	glyphName:'triangleLeft'},
		{gene: 'TPM1',	taxonomy: '1',	glyphSymbol:'^',	glyphName:'triangleUp'},
		{gene: 'CLU',	taxonomy: '2',	glyphSymbol:'h',	glyphName:'star6'},
		{gene: 'COL9A2',	taxonomy: '2',	glyphSymbol:'^',	glyphName:'triangleUp'},
		{gene: 'NOV',	taxonomy: '2',	glyphSymbol:'+',	glyphName:'plus'},
		{gene: 'RSPO3',	taxonomy: '2',	glyphSymbol:'*',	glyphName:'asterisk'},
		{gene: 'TOP2A',	taxonomy: '2',	glyphSymbol:'>',	glyphName:'triangleRight'},
		{gene: 'CRABP2',	taxonomy: '3',	glyphSymbol:'v',	glyphName:'triangleDown'},
		{gene: 'ISLR',	taxonomy: '3',	glyphSymbol:'>',	glyphName:'triangleRight'},
		{gene: 'PTN',	taxonomy: '3',	glyphSymbol:'+',	glyphName:'plus'},
		{gene: 'TBX18',	taxonomy: '3',	glyphSymbol:'+',	glyphName:'plus'},
		{gene: 'COL1A1',	taxonomy: '4',	glyphSymbol:'p',	glyphName:'star5'},
		{gene: 'EBF2',	taxonomy: '4',	glyphSymbol:'p',	glyphName:'star5'},
		{gene: 'LUM',	taxonomy: '4',	glyphSymbol:'d',	glyphName:'diamond'},
		{gene: 'TCF21',	taxonomy: '4',	glyphSymbol:'.',	glyphName:'point'},
		{gene: 'TRIL',	taxonomy: '4',	glyphSymbol:'v',	glyphName:'triangleDown'},
		{gene: 'COL1A2',	taxonomy: '5',	glyphSymbol:'^',	glyphName:'triangleUp'},
		{gene: 'EFNA5',	taxonomy: '5',	glyphSymbol:'*',	glyphName:'asterisk'},
		{gene: 'ELN',	taxonomy: '5',	glyphSymbol:'.',	glyphName:'point'},
		{gene: 'FBLN5',	taxonomy: '5',	glyphSymbol:'.',	glyphName:'point'},
		{gene: 'MFAP2',	taxonomy: '5',	glyphSymbol:'o',	glyphName:'circle'},
		{gene: 'NUSAP1',	taxonomy: '5',	glyphSymbol:'s',	glyphName:'square'},
		{gene: 'OGN',	taxonomy: '5',	glyphSymbol:'x',	glyphName:'cross'},
		{gene: 'MT1F',	taxonomy: '6',	glyphSymbol:'s',	glyphName:'square'},
		{gene: 'MT2A',	taxonomy: '6',	glyphSymbol:'>',	glyphName:'triangleRight'},
		{gene: 'SLC39A8',	taxonomy: '6',	glyphSymbol:'d',	glyphName:'diamond'},
		{gene: 'COL2A1',	taxonomy: '7',	glyphSymbol:'v',	glyphName:'triangleDown'},
		{gene: 'MYH6',	taxonomy: '7',	glyphSymbol:'x',	glyphName:'cross'},
		{gene: 'NPPA',	taxonomy: '7',	glyphSymbol:'o',	glyphName:'circle'},
		{gene: 'PAM',	taxonomy: '7',	glyphSymbol:'s',	glyphName:'square'},
		{gene: 'TBX5',	taxonomy: '7',	glyphSymbol:'o',	glyphName:'circle'},
		{gene: 'CCDC102B',	taxonomy: '8',	glyphSymbol:'^',	glyphName:'triangleUp'},
		{gene: 'COX4I2',	taxonomy: '8',	glyphSymbol:'s',	glyphName:'square'},
		{gene: 'SPARC',	taxonomy: '8',	glyphSymbol:'*',	glyphName:'asterisk'},
		{gene: 'CPE',	taxonomy: '9',	glyphSymbol:'+',	glyphName:'plus'},
		{gene: 'FOXS1',	taxonomy: '9',	glyphSymbol:'p',	glyphName:'star5'},
		{gene: 'ITLN1',	taxonomy: '9',	glyphSymbol:'*',	glyphName:'asterisk'},
		{gene: 'LRRN3',	taxonomy: '9',	glyphSymbol:'<',	glyphName:'triangleLeft'},
		{gene: 'MYRF',	taxonomy: '9',	glyphSymbol:'>',	glyphName:'triangleRight'},
		{gene: 'SBSPON',	taxonomy: '9',	glyphSymbol:'>',	glyphName:'triangleRight'},
		{gene: 'TNNT1',	taxonomy: '9',	glyphSymbol:'v',	glyphName:'triangleDown'},
		{gene: 'CDK1',	taxonomy: '10',	glyphSymbol:'<',	glyphName:'triangleLeft'},
		{gene: 'CLDN5',	taxonomy: '10',	glyphSymbol:'<',	glyphName:'triangleLeft'},
		{gene: 'GJA4',	taxonomy: '10',	glyphSymbol:'*',	glyphName:'asterisk'},
		{gene: 'TCIM',	taxonomy: '10',	glyphSymbol:'*',	glyphName:'asterisk'},
		{gene: 'TM4SF18',	taxonomy: '10',	glyphSymbol:'s',	glyphName:'square'},
		{gene: 'FAM210B',	taxonomy: '11',	glyphSymbol:'^',	glyphName:'triangleUp'},
		{gene: 'FAM46C',	taxonomy: '11',	glyphSymbol:'*',	glyphName:'asterisk'},
		{gene: 'FABP3',	taxonomy: '12',	glyphSymbol:'<',	glyphName:'triangleLeft'},
		{gene: 'LDB3',	taxonomy: '12',	glyphSymbol:'^',	glyphName:'triangleUp'},
		{gene: 'MYOZ2',	taxonomy: '12',	glyphSymbol:'p',	glyphName:'star5'},
		{gene: 'PLN',	taxonomy: '12',	glyphSymbol:'h',	glyphName:'star6'},
		{gene: 'TNNI1',	taxonomy: '12',	glyphSymbol:'d',	glyphName:'diamond'},
		{gene: 'ALDH1A1',	taxonomy: '14',	glyphSymbol:'s',	glyphName:'square'},
		{gene: 'ELAVL4',	taxonomy: '14',	glyphSymbol:'d',	glyphName:'diamond'},
		{gene: 'ISL1',	taxonomy: '14',	glyphSymbol:'o',	glyphName:'circle'},
		{gene: 'PCSK1N',	taxonomy: '14',	glyphSymbol:'v',	glyphName:'triangleDown'},
		{gene: 'STMN2',	taxonomy: '14',	glyphSymbol:'<',	glyphName:'triangleLeft'},
		];
	return out
}
