

function glyphAssignment()
{
    var out = [

        {gene:	'COL3A1'	,taxonomy:	'0'	,glyphSymbol:	'+'	,glyphName:	'plus'},
        {gene:	'PLN'	,taxonomy:	'0'	,glyphSymbol:	'p'	,glyphName:	'star5'},
        {gene:	'TMEM100'	,taxonomy:	'0'	,glyphSymbol:	'd'	,glyphName:	'diamond'},
        {gene:	'FABP3'	,taxonomy:	'1'	,glyphSymbol:	'>'	,glyphName:	'triangleRight'},
        {gene:	'HSPB7'	,taxonomy:	'1'	,glyphSymbol:	'v'	,glyphName:	'triangleDown'},
        {gene:	'MYH7'	,taxonomy:	'1'	,glyphSymbol:	'*'	,glyphName:	'asterisk'},
        {gene:	'MYL2'	,taxonomy:	'1'	,glyphSymbol:	's'	,glyphName:	'square'},
        {gene:	'MYL3'	,taxonomy:	'1'	,glyphSymbol:	'd'	,glyphName:	'diamond'},
        {gene:	'MYOM1'	,taxonomy:	'1'	,glyphSymbol:	'h'	,glyphName:	'star6'},
        {gene:	'NAV1'	,taxonomy:	'1'	,glyphSymbol:	'.'	,glyphName:	'point'},
        {gene:	'SLC8A1'	,taxonomy:	'1'	,glyphSymbol:	'x'	,glyphName:	'cross'},
        {gene:	'TNNI1'	,taxonomy:	'1'	,glyphSymbol:	'+'	,glyphName:	'plus'},
        {gene:	'TOP2A'	,taxonomy:	'1'	,glyphSymbol:	'<'	,glyphName:	'triangleLeft'},
        {gene:	'CLU'	,taxonomy:	'2'	,glyphSymbol:	'>'	,glyphName:	'triangleRight'},
        {gene:	'MYBPC3'	,taxonomy:	'2'	,glyphSymbol:	'h'	,glyphName:	'star6'},
        {gene:	'PTN'	,taxonomy:	'2'	,glyphSymbol:	'+'	,glyphName:	'plus'},
        {gene:	'COL1A1'	,taxonomy:	'3'	,glyphSymbol:	'<'	,glyphName:	'triangleLeft'},
        {gene:	'COL1A2'	,taxonomy:	'3'	,glyphSymbol:	'p'	,glyphName:	'star5'},
        {gene:	'ISLR'	,taxonomy:	'3'	,glyphSymbol:	'+'	,glyphName:	'plus'},
        {gene:	'PLVAP'	,taxonomy:	'3'	,glyphSymbol:	'h'	,glyphName:	'star6'},
        {gene:	'TBX5'	,taxonomy:	'3'	,glyphSymbol:	'x'	,glyphName:	'cross'},
        {gene:	'TCF21'	,taxonomy:	'3'	,glyphSymbol:	's'	,glyphName:	'square'},
        {gene:	'LUM'	,taxonomy:	'4'	,glyphSymbol:	's'	,glyphName:	'square'},
        {gene:	'CPE'	,taxonomy:	'5'	,glyphSymbol:	'.'	,glyphName:	'point'},
        {gene:	'CRABP2'	,taxonomy:	'5'	,glyphSymbol:	'x'	,glyphName:	'cross'},
        {gene:	'ELN'	,taxonomy:	'5'	,glyphSymbol:	'<'	,glyphName:	'triangleLeft'},
        {gene:	'FBLN5'	,taxonomy:	'5'	,glyphSymbol:	'*'	,glyphName:	'asterisk'},
        {gene:	'NUSAP1'	,taxonomy:	'5'	,glyphSymbol:	'^'	,glyphName:	'triangleUp'},
        {gene:	'FAM210B'	,taxonomy:	'6'	,glyphSymbol:	'p'	,glyphName:	'star5'},
        {gene:	'MT1F'	,taxonomy:	'6'	,glyphSymbol:	'^'	,glyphName:	'triangleUp'},
        {gene:	'MT2A'	,taxonomy:	'6'	,glyphSymbol:	'>'	,glyphName:	'triangleRight'},
        {gene:	'SBSPON'	,taxonomy:	'6'	,glyphSymbol:	'*'	,glyphName:	'asterisk'},
        {gene:	'COL2A1'	,taxonomy:	'7'	,glyphSymbol:	'h'	,glyphName:	'star6'},
        {gene:	'LDB3'	,taxonomy:	'7'	,glyphSymbol:	'*'	,glyphName:	'asterisk'},
        {gene:	'MYH6'	,taxonomy:	'7'	,glyphSymbol:	'o'	,glyphName:	'circle'},
        {gene:	'MYOZ2'	,taxonomy:	'7'	,glyphSymbol:	'x'	,glyphName:	'cross'},
        {gene:	'NPPA'	,taxonomy:	'7'	,glyphSymbol:	's'	,glyphName:	'square'},
        {gene:	'OGN'	,taxonomy:	'7'	,glyphSymbol:	'v'	,glyphName:	'triangleDown'},
        {gene:	'SLC39A8'	,taxonomy:	'7'	,glyphSymbol:	'.'	,glyphName:	'point'},
        {gene:	'SPARC'	,taxonomy:	'8'	,glyphSymbol:	'^'	,glyphName:	'triangleUp'},
        {gene:	'ITLN1'	,taxonomy:	'9'	,glyphSymbol:	'o'	,glyphName:	'circle'},
        {gene:	'MFAP2'	,taxonomy:	'9'	,glyphSymbol:	'd'	,glyphName:	'diamond'},
        {gene:	'MYRF'	,taxonomy:	'9'	,glyphSymbol:	'*'	,glyphName:	'asterisk'},
        {gene:	'RSPO3'	,taxonomy:	'9'	,glyphSymbol:	'.'	,glyphName:	'point'},
        {gene:	'SORBS2'	,taxonomy:	'9'	,glyphSymbol:	's'	,glyphName:	'square'},
        {gene:	'STMN2'	,taxonomy:	'9'	,glyphSymbol:	'v'	,glyphName:	'triangleDown'},
        {gene:	'CLDN5'	,taxonomy:	'10'	,glyphSymbol:	'^'	,glyphName:	'triangleUp'},
        {gene:	'GJA4'	,taxonomy:	'10'	,glyphSymbol:	'd'	,glyphName:	'diamond'},
        {gene:	'TM4SF18'	,taxonomy:	'10'	,glyphSymbol:	'.'	,glyphName:	'point'},
        {gene:	'PCSK1N'	,taxonomy:	'12'	,glyphSymbol:	'<'	,glyphName:	'triangleLeft'},
        {gene:	'TPM1'	,taxonomy:	'13'	,glyphSymbol:	'>'	,glyphName:	'triangleRight'},
        {gene:	'ALDH1A1'	,taxonomy:	'14'	,glyphSymbol:	'+'	,glyphName:	'plus'},
        {gene:	'ELAVL4'	,taxonomy:	'14'	,glyphSymbol:	'^'	,glyphName:	'triangleUp'},
        {gene:	'PAM'	,taxonomy:	'14'	,glyphSymbol:	'>'	,glyphName:	'triangleRight'},
        {gene:	'CCDC102B'	,taxonomy:	'less_active'	,glyphSymbol:	'.'	,glyphName:	'point'},
        {gene:	'CDK1'	,taxonomy:	'less_active'	,glyphSymbol:	's'	,glyphName:	'square'},
        {gene:	'COL9A2'	,taxonomy:	'less_active'	,glyphSymbol:	'o'	,glyphName:	'circle'},
        {gene:	'COX4I2'	,taxonomy:	'less_active'	,glyphSymbol:	'*'	,glyphName:	'asterisk'},
        {gene:	'EBF2'	,taxonomy:	'less_active'	,glyphSymbol:	's'	,glyphName:	'square'},
        {gene:	'EFNA5'	,taxonomy:	'less_active'	,glyphSymbol:	'd'	,glyphName:	'diamond'},
        {gene:	'FAM46C'	,taxonomy:	'less_active'	,glyphSymbol:	'o'	,glyphName:	'circle'},
        {gene:	'FOXS1'	,taxonomy:	'less_active'	,glyphSymbol:	's'	,glyphName:	'square'},
        {gene:	'ISL1'	,taxonomy:	'less_active'	,glyphSymbol:	'p'	,glyphName:	'star5'},
        {gene:	'LRRN3'	,taxonomy:	'less_active'	,glyphSymbol:	'x'	,glyphName:	'cross'},
        {gene:	'NOV'	,taxonomy:	'less_active'	,glyphSymbol:	'x'	,glyphName:	'cross'},
        {gene:	'TBX18'	,taxonomy:	'less_active'	,glyphSymbol:	'>'	,glyphName:	'triangleRight'},
        {gene:	'TCIM'	,taxonomy:	'less_active'	,glyphSymbol:	'*'	,glyphName:	'asterisk'},
        {gene:	'TNNT1'	,taxonomy:	'less_active'	,glyphSymbol:	'^'	,glyphName:	'triangleUp'},
        {gene:	'TRIL'	,taxonomy:	'less_active'	,glyphSymbol:	'p'	,glyphName:	'star5'},

        ];
    
    return out
}